### ISSUE TITLE
Add property to the Service schema to list the identify of the microservices implemented

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox-schemas#122]
For example, this property could be an array of enum values like "text_date_annotator", "text_person_name_annotator". This could be useful to identify the ability of a service to perform an action. Alternatively, one could try to call the expected endpoint and see if it's implemented (would return 404 or 500 or ?). Not sure how to identify if the endpoint does not exist and a 404/500 error.

**Comment by thomasyu888** [comment]
Decided for now that this won't happen.

**Comment by tschaffter** [comment]
@thomasyu888 I think that we don't really need this endpoint. From a user perspective, the page `/api/v1/ui` will expose what endpoints the tool implement. Initially we created this ticket having the tool evaluation in mind. However we can just send the requests to the tool submitted and if the request fails, then it means that something is wrong, i.e. either the tool does not implement the endpoint or the parameters specified lead to an error. Do you agree to close this ticket?

**Comment by thomasyu888** [comment]
I'm fine with that.  We don't really need the `/service` endpoint. It will be one less thing participants have to worry about and decreases the complexity of their submission by a little bit.

**Comment by tschaffter** [comment]
This ticket is not about removing the `/service` endpoint, but whether the `Service` object should provide information about the "types" of API that it implements. The initial motivation was to be able to use this information to have one submission and then automatically detect the type of API implemented and so which one we should test. As we moved away from this approach, there is no longer the need to modify the `Service` schema to include information about the types of APIs implemented. However we still keep the endpoint `/service` to get information about the tool (at least for now).
