### ISSUE TITLE
Review deidentifier specification

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox-schemas#123]
- Attempt to simplify variable / schema names
- Think about new endpoints for new use cases

**Comment by tschaffter** [comment]
Hey @gkowalski , would you like to review the OpenAPI specification in the folder `openapi/phi-deidentifier`?

**Comment by tschaffter** [comment]
Hey @ymnliu , could you also have a look at our PHI Deidentifier specifications before posting your feedback here? Thanks!

**Comment by ymnliu** [comment]
@tschaffter May you point me to the specification that needs to be reviewed? I am a bit lost when navigating the repos.

**Comment by tschaffter** [comment]
The OpenAPI specification of the input and output of the NLP Sandbox PHI Deidentifier is defined [here](https://github.com/nlpsandbox/nlpsandbox-schemas/tree/develop/openapi/phi-deidentifier). Feel free to contact @cascadianblue if you have question regarding the input/output or if you want to schedule a call with him so he can walk you through the design of the PHI Deidentifier.

**Comment by tschaffter** [comment]
@gkowalski @ymnliu Do you have feedback on the input and output of the PHI Deidentifier? If no I'll  go ahead and close this ticket.

**Comment by gkowalski** [comment]
I have not had time to review yet.

**Comment by tschaffter** [comment]
Done
