### ISSUE TITLE
Generalize AddressType to SubType

### ISSUE THREAD

**Issue by cascadianblue** [nlpsandbox/nlpsandbox-schemas#125]
What if we got rid of the `addressType` property for [`textPhyiscalAddressAnnotation`](https://github.com/nlpsandbox/nlpsandbox-schemas/blob/d68240020c644060c64ddd379ff54ef293b2704e/openapi/commons/components/schemas/TextPhysicalAddressAnnotation.yaml#L7) and put a `subType` property into [the `textAnnotation` schema](https://github.com/nlpsandbox/nlpsandbox-schemas/blob/d68240020c644060c64ddd379ff54ef293b2704e/openapi/commons/components/schemas/TextAnnotation.yaml#L1).

Essentially all of our annotation types have intuitive "sub-types". Dates have `YEAR`, `MONTH`, `DAY`; person names have `GIVEN NAME`, `FAMILY NAME`, `MIDDLE NAME` (or maybe those times `DOCTOR` and `PATIENT` ?)

These could be useful for De-IDing:
```
"Mary Williamson went to Seattle on the 12th" -> "[GIVEN_NAME] [LAST_NAME] went to [CITY] on the [DATE]"
```
would be more readable than `"[NAME] [NAME] went to [ADDRESS] on the [DATE]"`.

**Comment by tschaffter** [comment]
>Dates have YEAR, MONTH, DAY

**Comment by tschaffter** [comment]
> Dates have YEAR, MONTH, DAY

Dates do not have sub-types. Eample: `12/31/2020`

> person names have GIVEN NAME, FAMILY NAME, MIDDLE NAME (or maybe those times DOCTOR and PATIENT ?)

Having a `subType` for a patient would be confusing. The term sub-type is not well descriptive.

While deidentification is the primary application that we have in mind for annotator, we should attempt to keep them as agnostic as possible of a specific application.
