### ISSUE TITLE
Add a Confidence Threshold to DeidentificationConfig

### ISSUE THREAD

**Issue by cascadianblue** [nlpsandbox/nlpsandbox-schemas#126]
Add a new property to [DeidentificationConfig](https://github.com/nlpsandbox/nlpsandbox-schemas/blob/d68240020c644060c64ddd379ff54ef293b2704e/openapi/phi-deidentifier/components/schemas/DeidentificationConfig.yaml#L3) that only applies the `deidentificationStrategy` to an annotation if that annotation's confidence level is above the given threshold.

**Comment by cascadianblue** [comment]
What if the [`deidentifiedAnnotations` in `DeidentifyResponse`](https://github.com/nlpsandbox/nlpsandbox-schemas/blob/d68240020c644060c64ddd379ff54ef293b2704e/openapi/phi-deidentifier/components/responses/DeidentifyResponse.yaml#L6) each carried a boolean reflecting whether that annotation was applied/de-identified in the note?

It would be a bit involved to get this in, since each of `TextDateAnnotation`, `TextPhysicalAddressAnnotation` and `TextPersonNameAnnotation` would have to be copied to `DeidentifiedText_TYPE_HERE_Annotation` with just one added boolean property called `deidentified`.

**Comment by tschaffter** [comment]
> What if the deidentifiedAnnotations in DeidentifyResponse each carried a boolean reflecting whether that annotation was applied/de-identified in the note?

@cascadianblue I don't remember if we address this question on Friday. While we agreed to introduce to confidence threshold to the configurations/strategies, adding a boolean as suggested should no longer be necessary: either the annotations passed their respective threshold and are included in `DeidentifyResponse.originalAnnotations` and `DeidentifyResponse.deidentifiedAnnotations` or they are not.

> It would be a bit involved to get this in, since each of TextDateAnnotation, TextPhysicalAddressAnnotation and TextPersonNameAnnotation would have to be copied to DeidentifiedText_TYPE_HERE_Annotation with just one added boolean property called deidentified.

I don't understand this comment.

**Comment by cascadianblue** [comment]
> I don't understand this comment.

Well, I was trying to say that the way our schemas are arranged would make it tedious to create an `applied` boolean, because we'd have to do it for each annotation type.

It's a moot point, though, since your reasoning is right about the `applied` boolean not being necessary.
