### ISSUE TITLE
PersonType not returned in TextPersonNameAnnotation schema

### ISSUE THREAD

**Issue by thomasyu888** [nlpsandbox/nlpsandbox-schemas#134]
https://github.com/nlpsandbox/nlpsandbox-schemas/blob/develop/openapi/commons/components/schemas/TextPersonNameAnnotation.yaml

This is an expected key during scoring.

**Comment by tschaffter** [comment]
We have not settled on how to ask developers to address the "person type" and will probably not have the time to do so soon. For now, the infrastructure should not code anything that expect or would rely on the detection of "person type".

Tagging @yy6linda
