### ISSUE TITLE
Add /annotators endpoint to PHI-Deidentifier

### ISSUE THREAD

**Issue by cascadianblue** [nlpsandbox/nlpsandbox-schemas#136]
We want to get info from the `/service` endpoint of the annotators and pass it along to the client

**Comment by tschaffter** [comment]
@cascadianblue The title mentions `/annotators` but the original message mention `/service`, which is confusing. On Friday, I clarified the purpose of `/service`. Ideally I would like all NLP Sandbox service to return the same schema for `/service`, so we need to look somewhere else to get information about the annotators used (e.g. the service name and version). Did you have chance to identify how to achieve this?

**Comment by cascadianblue** [comment]
@tschaffter my thinking is that the `phi-deidentifier` should go and get the service info from each annotator (i.e. from `http://date-annotator:8080/service/`, `http://physical-address-annotator:8080/service`, `http://person-name-annotator:8080/service`), compile it as an array, and expose it to the web/React client at the URL `/annotators`

**Comment by tschaffter** [comment]
This ticket is addressed by the new path `/tool/dependencies` now in the branch `develop`.
