### ISSUE TITLE
Tool version schema pattern doesn't match example

### ISSUE THREAD

**Issue by thomasyu888** [nlpsandbox/nlpsandbox-schemas#163]
### Problem description

Tool version pattern doesn't seem to map to semantic versioning

#### Steps to reproduce the issue

```
npm run lint:ibm --entrypoint=openapi/person-name-annotator/openapi.yaml

warnings

  Message :   `version` property should match pattern `^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$`
  Path    :   paths./tool.get.responses.200.content.application/json.schema.example.version
  Line    :   83

  Message :   `version` property should match pattern `^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$`
  Path    :   paths./tool/dependencies.get.responses.200.content.application/json.schema.properties.toolDependencies.items.example.version
  Line    :   101

  Message :   `version` property should match pattern `^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$`
  Path    :   components.schemas.Tool.example.version
  Line    :   341

  Message :   `version` property should match pattern `^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$`
  Path    :   components.schemas.ToolDependencies.properties.toolDependencies.items.example.version
  Line    :   357

```

#### Expected behavior

I think the pattern should work or else I think it will cause us problems downstream.

#### Extra information
This used to be an error in the IBM openapi version 0.31.1 linter, but isn't anymore in 0.34.1.  I also found this: https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string

**Comment by tschaffter** [comment]
I created the above PR (work in progress). There are two issues I'm trying to solve:

1. Turn the warnings that you reported and makes then "errors"
2. The regex displayed in the warnings is the regex I found on the page you referenced, which I escaped for a reason (maybe due to an error downstream?). The warning disappears if I use the un-escaped regex, so I'm going with it for now.

**Comment by tschaffter** [comment]
The warning message is returned by the library [spectral](https://github.com/stoplightio/spectral/issues/1115) used by the IBM validator.
