### ISSUE TITLE
Add contact annotation data schema

### ISSUE THREAD

**Issue by yy6linda** [nlpsandbox/nlpsandbox-schemas#193]
### Tool description
Add a data schema for contact annotation

### Tool input
 The tool would be built based on existing NLPSandbox.io schemas for address and person name annotation

### Tool output
 The output will be the data schemas for contact annotation

### Contact information

**Your name:** Yao Yan
**Your email address:** yy6linda@gmail.com
**Name of your organization:** Sage Bionetworks

**Comment by tschaffter** [comment]
@yy6linda Shall we name this new tool `contact-annotator`?

Here is [the PR](https://github.com/nlpsandbox/nlpsandbox-schemas/pull/195/files) where we are adding the OpenAPI specification (schemas) of the COVID-19 Symptom annotator. The PR is a work in progress but you can see the files that needed to be created/updated. Please follow this example to create the PR that implements this ticket.
