### ISSUE TITLE
Write description for the Date annotation task

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox-schemas#37]
This description will be used on the NLP Sandbox website.

@yy6linda Our date annotation task is based on the content of the 2014 i2b2 dataset. This dataset includes dates (MM/DD/YYYY and similar) but also day of the week, month, etc. Are all those date/time information considered as HIPAA PHI? We should categorize the date/time information that are relevant for HIPAA based on the date format (depends on https://github.com/Sage-Bionetworks/nlp-sandbox-analysis/issues/5)

**Comment by tschaffter** [comment]
## Update

@yy6linda has started to write the documentation for each task on the Synapse website.

**Comment by yy6linda** [comment]
Description added in this [wiki page](https://www.synapse.org/#!Synapse:syn22277124/wiki/607935).

**Comment by tschaffter** [comment]
@yy6linda Please create a section called `Task` and then describe each task on a sub-page as asked on Slack. As the number of tasks will increase, it will become difficult to quickly locate the relevant information if everything is dumped to one page as currently done.

**Comment by yy6linda** [comment]
Task section created. @tschaffter Please take a look and review the changes.

**Comment by tschaffter** [comment]
Thanks @yy6linda . It's a good start. I feel like we need to write some text to provide more background to the developers. Just starting with `Input: ...` and `Output: ...` is a bit rough. :sweat_smile:
