### ISSUE TITLE
Identify schemas for evaluations

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox-schemas#38]
Work in progress: https://lucid.app/lucidchart/d53fc967-6d6b-4807-83b0-c1480a43012c

![image](https://user-images.githubusercontent.com/3056480/95994218-df00ac80-0de4-11eb-8e65-247c1be21fea.png)

**Comment by tschaffter** [comment]
## Update

The motivation of this exercise is to find a way to report performance for different definition of PHI (e.g. HIPAA, I2B2).

@yy6linda For the three NLP tasks that we are currently considering, does it make sense to report performance for "HIPAA" and "I2B2" as defined in the table below?

![image](https://user-images.githubusercontent.com/3056480/103950522-dec93200-50f1-11eb-8ec0-d92592cc50ee.png)

[Source](url
![image](https://user-images.githubusercontent.com/3056480/103950533-e4bf1300-50f1-11eb-9850-9dcd862db7c0.png)
)

**Comment by yy6linda** [comment]
What does the binary in binary token mean?

**Comment by tschaffter** [comment]
@yy6linda We have reviewed these categories in the past but I forgot what Binary means too. Please refer to the google doc or the original manuscript of the challenge organizers.

**Comment by yy6linda** [comment]
The category has been reviewed and we have identified schemas for evaluation. Details see the [wiki page](https://www.synapse.org/#!Synapse:syn22277124/wiki/607935)

**Comment by tschaffter** [comment]
The markdown example on the page you reference include properties like `"noteId": "110-03"` that we have agreed to remove as developers are not asked to provide it. Never mind, I'll remove them myself.

**Comment by thomasyu888** [comment]
@tschaffter, There is some confusion because the evaluation script requires `noteId` but participants aren't supposed to write their output that way.
